In [1]:
import pandas as pd
from pathlib import Path


PROJECT_ROOT = Path(
    r"C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation"
)


GRAPH_DIR = PROJECT_ROOT / "final_data" / "graph"


edges = pd.read_csv(
    GRAPH_DIR / "graph_edges.csv"
)


stats = pd.read_csv(
    GRAPH_DIR / "graph_user_statistics.csv"
)


print("="*90)
print("GRAPH EDGES")
print("="*90)

print(edges.shape)
print(edges.head())
print(edges.columns.tolist())


print("\n")


print("="*90)
print("GRAPH USER STATISTICS")
print("="*90)

print(stats.shape)
print(stats.head())
print(stats.columns.tolist())

GRAPH EDGES
(796485, 6)
          source           target relation  source_in_dataset  \
0        chaiiee  SajjadSade48567  follows               True   
1      dr_lizzii  SajjadSade48567  follows              False   
2  nathaniel2026  SajjadSade48567  follows              False   
3    julian270zi  SajjadSade48567  follows              False   
4    kongoshadha  SajjadSade48567  follows               True   

   target_in_dataset  internal_edge  
0               True           True  
1               True          False  
2               True          False  
3               True          False  
4               True           True  
['source', 'target', 'relation', 'source_in_dataset', 'target_in_dataset', 'internal_edge']


GRAPH USER STATISTICS
(3443, 8)
             id      screen_name  \
0  1.780000e+18  SajjadSade48567   
1  2.511595e+08        mojtaba2a   
2  1.790000e+18          niya64_   
3  1.870000e+18     arash_the3rd   
4  1.520000e+18   kaveAhanga2022   

              

In [2]:
internal_edges = edges[
    edges["internal_edge"] == True
].copy()


print("="*90)
print("INTERNAL GRAPH")
print("="*90)

print(
    internal_edges.shape
)

print(
    internal_edges.head()
)

INTERNAL GRAPH
(284743, 6)
            source           target relation  source_in_dataset  \
0          chaiiee  SajjadSade48567  follows               True   
4      kongoshadha  SajjadSade48567  follows               True   
5     KAryayy80688  SajjadSade48567  follows               True   
6       Roobahyab1  SajjadSade48567  follows               True   
7  SajjadSade48567             grok  follows               True   

   target_in_dataset  internal_edge  
0               True           True  
4               True           True  
5               True           True  
6               True           True  
7               True           True  


In [3]:
import numpy as np


# All nodes from internal graph

nodes = pd.unique(
    pd.concat(
        [
            internal_edges["source"],
            internal_edges["target"]
        ]
    )
)


print("="*90)
print("GRAPH NODES")
print("="*90)

print(
    "Number of nodes:",
    len(nodes)
)


print(
    nodes[:10]
)



# Node mapping

node_to_id = {
    node: idx
    for idx, node in enumerate(nodes)
}


print("\nMapping sample:")

for k,v in list(node_to_id.items())[:5]:
    print(k, "->", v)

GRAPH NODES
Number of nodes: 13466
<StringArray>
[        'chaiiee',     'kongoshadha',    'KAryayy80688',      'Roobahyab1',
 'SajjadSade48567',         'Egoods1',       'mojtaba2a', 'rend_e_kharabat',
     'mjm71582789',         'niya64_']
Length: 10, dtype: str

Mapping sample:
chaiiee -> 0
kongoshadha -> 1
KAryayy80688 -> 2
Roobahyab1 -> 3
SajjadSade48567 -> 4


In [5]:
import pandas as pd
from pathlib import Path


PROJECT_ROOT = Path(
    r"C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation"
)


TABULAR_DIR = (
    PROJECT_ROOT /
    "final_data" /
    "splits" /
    "tabular"
)


print(TABULAR_DIR)


train_tabular = pd.read_csv(
    TABULAR_DIR / "train_tabular.csv"
)

val_tabular = pd.read_csv(
    TABULAR_DIR / "validation_tabular.csv"
)

test_tabular = pd.read_csv(
    TABULAR_DIR / "test_tabular.csv"
)


print("="*90)
print("TABULAR SPLITS")
print("="*90)


print("Train:", train_tabular.shape)
print("Validation:", val_tabular.shape)
print("Test:", test_tabular.shape)


print(train_tabular.head())

C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\final_data\splits\tabular
TABULAR SPLITS
Train: (671, 43)
Validation: (144, 43)
Test: (144, 43)
      screen_name        user_key  label_binary  followers_count  \
0       Dokhi_sag       dokhi_sag             0         2.260710   
1    History_Wall    history_wall             0        -0.661092   
2  corrrdeliiiaaa  corrrdeliiiaaa             0        -0.974405   
3      ahmad_313m      ahmad_313m             0        -0.103043   
4   kouresh_kabir   kouresh_kabir             0         0.070104   

   friends_count  favourites_count  listed_count  media_count  statuses_count  \
0       1.922168         -0.717008      0.800936    -0.218288       -0.648278   
1      -0.412186         -0.211043     -0.671950    -1.161989       -0.956884   
2      -1.492217          1.227229      0.000000     1.007042        1.017413   
3      -2.765518         -2.411713      0.714903    -0.881804       -1.224861   
4       0.59280

In [6]:
# Check labeled users coverage in graph


gold_users = pd.concat(
    [
        train_tabular,
        val_tabular,
        test_tabular
    ],
    ignore_index=True
)


gold_users["screen_name_norm"] = (
    gold_users["screen_name"]
    .astype(str)
    .str.lower()
)


graph_nodes_norm = {
    str(n).lower()
    for n in nodes
}


matched_users = [
    u
    for u in gold_users["screen_name_norm"]
    if u in graph_nodes_norm
]


print("="*90)
print("GRAPH LABEL COVERAGE")
print("="*90)


print(
    "Gold users:",
    len(gold_users)
)


print(
    "Matched in graph:",
    len(matched_users)
)


print(
    "Coverage:",
    f"{len(matched_users)/len(gold_users)*100:.2f}%"
)

GRAPH LABEL COVERAGE
Gold users: 959
Matched in graph: 935
Coverage: 97.50%


In [7]:
import torch
import numpy as np


# Source and target node ids

src = internal_edges["source"].map(
    node_to_id
)

dst = internal_edges["target"].map(
    node_to_id
)


# Remove possible missing mappings

mask = (
    src.notna()
    &
    dst.notna()
)


src = src[mask].astype(int)
dst = dst[mask].astype(int)



# Make graph undirected

edge_index = np.vstack(
    [
        np.concatenate(
            [
                src.values,
                dst.values
            ]
        ),

        np.concatenate(
            [
                dst.values,
                src.values
            ]
        )
    ]
)


edge_index = torch.tensor(
    edge_index,
    dtype=torch.long
)


print("="*90)
print("EDGE INDEX")
print("="*90)

print(
    "Shape:",
    edge_index.shape
)

print(
    edge_index[:, :5]
)

EDGE INDEX
Shape: torch.Size([2, 569486])
tensor([[    0,     1,     2,     3,     4],
        [    4,     4,     4,     4, 11597]])


In [8]:
from collections import Counter


# Convert edges to numpy

src_nodes = edge_index[0].numpy()
dst_nodes = edge_index[1].numpy()


# In / Out degree

out_degree = Counter(src_nodes)
in_degree = Counter(dst_nodes)



num_nodes = len(nodes)


graph_features = []


for i in range(num_nodes):

    in_d = in_degree.get(i, 0)
    out_d = out_degree.get(i, 0)

    graph_features.append(
        [
            in_d,
            out_d,
            in_d + out_d
        ]
    )


graph_features = np.array(
    graph_features,
    dtype=np.float32
)


print("="*90)
print("GRAPH NODE FEATURES")
print("="*90)


print(
    "Shape:",
    graph_features.shape
)


print(
    graph_features[:5]
)

GRAPH NODE FEATURES
Shape: (13466, 3)
[[ 40.  40.  80.]
 [131. 131. 262.]
 [ 44.  44.  88.]
 [300. 300. 600.]
 [ 31.  31.  62.]]


In [9]:
import torch


num_nodes = len(nodes)


# Initialize labels
labels = np.full(
    num_nodes,
    -1,
    dtype=np.int64
)


# Normalize graph nodes

node_lookup = {
    str(k).lower(): v
    for k, v in node_to_id.items()
}



# Add labels from gold dataset

matched_count = 0


for _, row in gold_users.iterrows():

    username = (
        str(row["screen_name"])
        .lower()
    )


    if username in node_lookup:

        node_id = node_lookup[username]

        labels[node_id] = int(
            row["label_binary"]
        )

        matched_count += 1



labels = torch.tensor(
    labels,
    dtype=torch.long
)



print("="*90)
print("GRAPH LABEL VECTOR")
print("="*90)


print(
    "Total nodes:",
    num_nodes
)

print(
    "Labeled nodes:",
    (labels != -1).sum().item()
)


print(
    "Missing labels:",
    (labels == -1).sum().item()
)


print(
    "Label distribution:"
)

print(
    torch.bincount(
        labels[labels!=-1]
    )
)

GRAPH LABEL VECTOR
Total nodes: 13466
Labeled nodes: 935
Missing labels: 12531
Label distribution:
tensor([752, 183])


In [10]:
# Create graph masks

train_mask = np.zeros(
    num_nodes,
    dtype=bool
)

val_mask = np.zeros(
    num_nodes,
    dtype=bool
)

test_mask = np.zeros(
    num_nodes,
    dtype=bool
)



def assign_mask(df, mask):

    count = 0

    for _, row in df.iterrows():

        username = (
            str(row["screen_name"])
            .lower()
        )

        if username in node_lookup:

            node_id = node_lookup[username]

            mask[node_id] = True

            count += 1

    return count



train_count = assign_mask(
    train_tabular,
    train_mask
)


val_count = assign_mask(
    val_tabular,
    val_mask
)


test_count = assign_mask(
    test_tabular,
    test_mask
)



print("="*90)
print("GRAPH MASKS")
print("="*90)


print(
    "Train nodes:",
    train_count
)

print(
    "Validation nodes:",
    val_count
)

print(
    "Test nodes:",
    test_count
)

GRAPH MASKS
Train nodes: 657
Validation nodes: 138
Test nodes: 140


In [12]:
from torch_geometric.data import Data


# Convert features to tensor

x = torch.tensor(
    graph_features,
    dtype=torch.float
)


# Convert masks

train_mask = torch.tensor(
    train_mask,
    dtype=torch.bool
)

val_mask = torch.tensor(
    val_mask,
    dtype=torch.bool
)

test_mask = torch.tensor(
    test_mask,
    dtype=torch.bool
)



graph_data = Data(
    x=x,
    edge_index=edge_index,
    y=labels,
    train_mask=train_mask,
    val_mask=val_mask,
    test_mask=test_mask
)


print("="*90)
print("PYTORCH GEOMETRIC DATA")
print("="*90)

print(graph_data)


print("\nNodes:")
print(graph_data.num_nodes)


print("Edges:")
print(graph_data.num_edges)


print("Features:")
print(graph_data.num_node_features)


print("Train labels:")
print(graph_data.train_mask.sum())


print("Validation labels:")
print(graph_data.val_mask.sum())


print("Test labels:")
print(graph_data.test_mask.sum())

PYTORCH GEOMETRIC DATA
Data(x=[13466, 3], edge_index=[2, 569486], y=[13466], train_mask=[13466], val_mask=[13466], test_mask=[13466])

Nodes:
13466
Edges:
569486
Features:
3
Train labels:
tensor(657)
Validation labels:
tensor(138)
Test labels:
tensor(140)


In [13]:
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.nn import GCNConv


class GCNClassifier(nn.Module):

    def __init__(self, input_dim=3, hidden_dim=64):

        super().__init__()

        self.conv1 = GCNConv(
            input_dim,
            hidden_dim
        )


        self.conv2 = GCNConv(
            hidden_dim,
            32
        )


        self.classifier = nn.Linear(
            32,
            2
        )


    def forward(self, data):

        x = data.x
        edge_index = data.edge_index


        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = F.dropout(
            x,
            p=0.3,
            training=self.training
        )


        x = self.conv2(
            x,
            edge_index
        )

        x = F.relu(x)


        x = self.classifier(
            x
        )


        return x



gcn_model = GCNClassifier()


print("="*90)
print("GCN MODEL")
print("="*90)

print(gcn_model)

GCN MODEL
GCNClassifier(
  (conv1): GCNConv(3, 64)
  (conv2): GCNConv(64, 32)
  (classifier): Linear(in_features=32, out_features=2, bias=True)
)


In [14]:
import torch.optim as optim


# Class weights

class_counts = torch.bincount(
    labels[labels != -1]
)


class_weights = (
    class_counts.sum()
    /
    (len(class_counts) * class_counts)
)


class_weights = class_weights.float()


print("="*90)
print("CLASS WEIGHTS")
print("="*90)

print(class_counts)
print(class_weights)



device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)


graph_data = graph_data.to(device)

gcn_model = GCNClassifier().to(device)


criterion = nn.CrossEntropyLoss(
    weight=class_weights.to(device)
)


optimizer = optim.AdamW(
    gcn_model.parameters(),
    lr=0.01,
    weight_decay=5e-4
)


print("\nDevice:")
print(device)

CLASS WEIGHTS
tensor([752, 183])
tensor([0.6217, 2.5546])

Device:
cpu


In [15]:
import time


def train_gcn(
    model,
    data,
    optimizer,
    criterion,
    epochs=200
):

    best_val_loss = float("inf")
    best_state = None


    for epoch in range(1, epochs + 1):

        model.train()

        optimizer.zero_grad()


        out = model(data)


        loss = criterion(
            out[data.train_mask],
            data.y[data.train_mask]
        )


        loss.backward()

        optimizer.step()



        # Validation

        model.eval()

        with torch.no_grad():

            val_out = model(data)

            val_loss = criterion(
                val_out[data.val_mask],
                data.y[data.val_mask]
            )


        if val_loss < best_val_loss:

            best_val_loss = val_loss

            best_state = (
                model.state_dict()
                .copy()
            )


        if epoch % 20 == 0:

            print(
                f"Epoch [{epoch}/{epochs}] "
                f"Train Loss: {loss.item():.4f} "
                f"Val Loss: {val_loss.item():.4f}"
            )


    print("\nTraining completed")


    model.load_state_dict(
        best_state
    )


    print(
        "Best GCN model restored"
    )


    return model

In [16]:
gcn_model = train_gcn(
    gcn_model,
    graph_data,
    optimizer,
    criterion,
    epochs=200
)

Epoch [20/200] Train Loss: 0.7989 Val Loss: 0.7562
Epoch [40/200] Train Loss: 0.7280 Val Loss: 0.7121
Epoch [60/200] Train Loss: 0.7036 Val Loss: 0.6937
Epoch [80/200] Train Loss: 0.7009 Val Loss: 0.6928
Epoch [100/200] Train Loss: 0.6970 Val Loss: 0.6936
Epoch [120/200] Train Loss: 0.6929 Val Loss: 0.6937
Epoch [140/200] Train Loss: 0.6935 Val Loss: 0.6945
Epoch [160/200] Train Loss: 0.6934 Val Loss: 0.6949
Epoch [180/200] Train Loss: 0.6957 Val Loss: 0.6949
Epoch [200/200] Train Loss: 0.6956 Val Loss: 0.6956

Training completed
Best GCN model restored


In [17]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

import numpy as np


def evaluate_gcn(model, data, mask, name):

    model.eval()

    with torch.no_grad():

        logits = model(data)

        probs = torch.softmax(
            logits,
            dim=1
        )[:,1]


        preds = (
            probs >= 0.5
        ).long()


    y_true = (
        data.y[mask]
        .cpu()
        .numpy()
    )


    y_pred = (
        preds[mask]
        .cpu()
        .numpy()
    )


    y_prob = (
        probs[mask]
        .cpu()
        .numpy()
    )


    print("="*90)
    print(name)
    print("="*90)


    print(
        "Accuracy:",
        round(
            accuracy_score(y_true,y_pred),
            4
        )
    )

    print(
        "Precision:",
        round(
            precision_score(
                y_true,
                y_pred,
                zero_division=0
            ),
            4
        )
    )

    print(
        "Recall:",
        round(
            recall_score(
                y_true,
                y_pred,
                zero_division=0
            ),
            4
        )
    )

    print(
        "F1:",
        round(
            f1_score(
                y_true,
                y_pred,
                zero_division=0
            ),
            4
        )
    )


    print(
        "ROC_AUC:",
        round(
            roc_auc_score(
                y_true,
                y_prob
            ),
            4
        )
    )


    print(
        "PR_AUC:",
        round(
            average_precision_score(
                y_true,
                y_prob
            ),
            4
        )
    )


    print("\nConfusion Matrix:")
    print(
        confusion_matrix(
            y_true,
            y_pred
        )
    )


    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            y_pred,
            target_names=[
                "Human",
                "Bot"
            ]
        )
    )


    return {
        "Accuracy": accuracy_score(y_true,y_pred),
        "Precision": precision_score(y_true,y_pred,zero_division=0),
        "Recall": recall_score(y_true,y_pred,zero_division=0),
        "F1": f1_score(y_true,y_pred,zero_division=0),
        "ROC_AUC": roc_auc_score(y_true,y_prob),
        "PR_AUC": average_precision_score(y_true,y_prob)
    }

In [18]:
gcn_val_results = evaluate_gcn(
    gcn_model,
    graph_data,
    graph_data.val_mask,
    "GCN Validation"
)


gcn_test_results = evaluate_gcn(
    gcn_model,
    graph_data,
    graph_data.test_mask,
    "GCN Test"
)

GCN Validation
Accuracy: 0.5507
Precision: 0.2131
Recall: 0.4815
F1: 0.2955
ROC_AUC: 0.4541
PR_AUC: 0.1745

Confusion Matrix:
[[63 48]
 [14 13]]

Classification Report:
              precision    recall  f1-score   support

       Human       0.82      0.57      0.67       111
         Bot       0.21      0.48      0.30        27

    accuracy                           0.55       138
   macro avg       0.52      0.52      0.48       138
weighted avg       0.70      0.55      0.60       138

GCN Test
Accuracy: 0.5714
Precision: 0.1633
Recall: 0.2963
F1: 0.2105
ROC_AUC: 0.4602
PR_AUC: 0.1884

Confusion Matrix:
[[72 41]
 [19  8]]

Classification Report:
              precision    recall  f1-score   support

       Human       0.79      0.64      0.71       113
         Bot       0.16      0.30      0.21        27

    accuracy                           0.57       140
   macro avg       0.48      0.47      0.46       140
weighted avg       0.67      0.57      0.61       140



In [19]:
import pandas as pd
from pathlib import Path


RESULTS_DIR = (
    PROJECT_ROOT /
    "results"
)

RESULTS_DIR.mkdir(
    exist_ok=True
)


gcn_results = pd.DataFrame(
    [
        {
            "Model": "GCN-Degree-Only Validation",
            **gcn_val_results
        },
        {
            "Model": "GCN-Degree-Only Test",
            **gcn_test_results
        }
    ]
)


save_path = (
    RESULTS_DIR /
    "graph_baseline_results.csv"
)


gcn_results.to_csv(
    save_path,
    index=False
)


print("="*90)
print("GRAPH BASELINE RESULTS SAVED")
print("="*90)

print(save_path)

print()

print(gcn_results)

GRAPH BASELINE RESULTS SAVED
C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\results\graph_baseline_results.csv

                        Model  Accuracy  Precision    Recall        F1  \
0  GCN-Degree-Only Validation  0.550725   0.213115  0.481481  0.295455   
1        GCN-Degree-Only Test  0.571429   0.163265  0.296296  0.210526   

    ROC_AUC    PR_AUC  
0  0.454121  0.174515  
1  0.460177  0.188417  


In [20]:
from pathlib import Path


GRAPH_DIR = (
    PROJECT_ROOT /
    "final_data" /
    "graph"
)


GRAPH_DIR.mkdir(
    exist_ok=True
)


print(GRAPH_DIR)

C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\final_data\graph


In [21]:
torch.save(
    graph_data.cpu(),
    GRAPH_DIR / "graph_data_degree_only.pt"
)


print(
    "Graph data saved"
)

Graph data saved


In [22]:
import pickle


with open(
    GRAPH_DIR / "node_to_id.pkl",
    "wb"
) as f:

    pickle.dump(
        node_to_id,
        f
    )


print(
    "Node mapping saved"
)

Node mapping saved


In [23]:
np.save(
    GRAPH_DIR / "degree_features.npy",
    graph_features
)


print(
    "Degree features saved"
)

Degree features saved
